name: stg
favicon: null
layout_spectrum: 0.020297454437240958
typography_spectrum: 0.08369046729058027
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.07567458273842931
  lightness: 0.7108235820196569
  saturation: 0.7514450752642006
  rhythmicContrast: 0.15762644028291106
purpose: []
